import random
character=['a','b','c','d','e','f','g']
number=['0','1','2','3','4','5']
symbol=['!','@','#','$','%','&']
c=int(input("Enter the character :"))
n=int(input("enter the number:"))
s=int(input("enter the symbol"))
print("***********AUTOGENERATED PASSWORd**********")
print()
for i in range(50):
    total_length=c+n+s
    password=[]
    for i in range(c):
      password +=random.choice(character)
    for i in range(n):
      password +=random.choice(number)
    for i in range(s):
      password +=random.choice(symbol)
    random.shuffle(password)
    your_pass="".join(password)
    print("Length of the Password",total_length)
    print(your_pass)



